name: Move all source to root
on: workflow_dispatch
jobs:
  move-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Move all files out of blog-sdlow
        run: mv ./blog-sdlow/* ./
      - name: Delete empty dir
        run: rm -rf blog-sdlow
      - name: Git config & commit
        run: |
          git config --global user.name "sdlow"
          git config --global user.email "2809898553@qq.com"
          git add .
          git commit -m "Move hexo source to repo root"
          git push
